import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-gallery',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './gallery.component.html',
  styleUrl: './gallery.component.css'
})
export class GalleryComponent {
  galleryItems = [ 
    { type: 'image', src: '/images/Gallery/image_3.jpg' },
    { type: 'image', src: '/images/Gallery/image_4.jpg' },
    { type: 'image', src: '/images/Gallery/image_5.jpg' },
    { type: 'image', src: '/images/Gallery/image_6.jpg' },
    { type: 'image', src: '/images/Gallery/image_7.jpg' },
    { type: 'image', src: '/images/Gallery/image_8.jpg' },
    { type: 'image', src: '/images/Gallery/image_9.jpg' },
    { type: 'image', src: '/images/Gallery/image_10.jpg' },
    { type: 'image', src: '/images/Gallery/image_11.jpg' },
    { type: 'image', src: '/images/Gallery/image_12.jpg' },
    { type: 'image', src: '/images/Gallery/image_13.jpg' },
    { type: 'image', src: '/images/Gallery/image_14.jpg' },
    { type: 'image', src: '/images/Gallery/image_15.jpg' },
    { type: 'image', src: '/images/Gallery/image_16.jpg' },
    { type: 'image', src: '/images/Gallery/image_17.jpg' },
    { type: 'image', src: '/images/Gallery/image_18.jpg' },
    { type: 'image', src: '/images/Gallery/image_19.jpg' },
    { type: 'image', src: '/images/Gallery/image_20.jpg' },
    { type: 'image', src: '/images/Gallery/image_21.jpg' },
    { type: 'image', src: '/images/Gallery/image_22.jpg' },
    { type: 'image', src: '/images/Gallery/image_23.jpg' },
    { type: 'image', src: '/images/Gallery/image_24.jpg' },
    { type: 'image', src: '/images/Gallery/image_25.jpg' },
    { type: 'image', src: '/images/Gallery/image_26.jpg' },
    { type: 'image', src: '/images/Gallery/image_27.jpg' },
    { type: 'image', src: '/images/Gallery/image_28.jpg' },
    { type: 'image', src: '/images/Gallery/image_29.jpg' },
    { type: 'image', src: '/images/Gallery/image_30.jpg' },
    { type: 'image', src: '/images/Gallery/image_31.jpg' },
    { type: 'image', src: '/images/Gallery/image_32.jpg' },
    { type: 'image', src: '/images/Gallery/image_33.jpg' },
    { type: 'image', src: '/images/Gallery/image_34.jpg' },
    { type: 'image', src: '/images/Gallery/image_35.jpg' },
    { type: 'image', src: '/images/Gallery/image_36.jpg' },
    { type: 'image', src: '/images/Gallery/image_37.jpg' },
    { type: 'image', src: '/images/Gallery/image_38.jpg' },
    { type: 'image', src: '/images/Gallery/image_39.jpg' },
    { type: 'image', src: '/images/Gallery/image_40.jpg' },
    { type: 'image', src: '/images/Gallery/image_41.jpg' },
    { type: 'image', src: '/images/Gallery/image_42.jpg' },
    { type: 'image', src: '/images/Gallery/image_43.jpg' },
    { type: 'image', src: '/images/Gallery/image_44.jpg' },
    { type: 'image', src: '/images/Gallery/image_45.jpg' },
    { type: 'image', src: '/images/Gallery/image_46.jpg' },
    { type: 'image', src: '/images/Gallery/image_47.jpg' },
    { type: 'image', src: '/images/Gallery/image_48.jpg' },
    { type: 'image', src: '/images/Gallery/image_49.jpg' },
    { type: 'image', src: '/images/Gallery/image_50.jpg' },
    { type: 'image', src: '/images/Gallery/image_51.jpg' },
    { type: 'image', src: '/images/Gallery/image_52.jpg' },
    { type: 'image', src: '/images/Gallery/image_53.jpg' },
    { type: 'image', src: '/images/Gallery/image_54.jpg' },
    { type: 'image', src: '/images/Gallery/image_55.jpg' },
    { type: 'image', src: '/images/Gallery/image_56.jpg' },
    { type: 'image', src: '/images/Gallery/image_57.jpg' },
    { type: 'image', src: '/images/Gallery/image_58.jpg' },
    { type: 'image', src: '/images/Gallery/image_59.jpg' },
    { type: 'image', src: '/images/Gallery/image_60.jpg' },
    { type: 'image', src: '/images/Gallery/image_61.jpg' },
    { type: 'image', src: '/images/Gallery/image_62.jpg' },
    { type: 'image', src: '/images/Gallery/image_63.jpg' },
    { type: 'image', src: '/images/Gallery/image_64.jpg' },
    { type: 'image', src: '/images/Gallery/image_65.jpg' },
    { type: 'image', src: '/images/Gallery/image_66.jpg' },
    { type: 'image', src: '/images/Gallery/image_67.jpg' },
    { type: 'image', src: '/images/Gallery/image_68.jpg' },
    { type: 'image', src: '/images/Gallery/image_69.jpg' },
    { type: 'image', src: '/images/Gallery/image_70.jpg' },
    { type: 'image', src: '/images/Gallery/image_71.jpg' },
    { type: 'image', src: '/images/Gallery/image_72.jpg' },
    { type: 'image', src: '/images/Gallery/image_73.jpg' },
    { type: 'image', src: '/images/Gallery/image_74.jpg' },
    { type: 'image', src: '/images/Gallery/image_75.jpg' },
    { type: 'image', src: '/images/Gallery/image_76.jpg' },
    { type: 'image', src: '/images/Gallery/image_77.jpg' },
    { type: 'image', src: '/images/Gallery/image_78.jpg' },
    { type: 'image', src: '/images/Gallery/image_79.jpg' },
    { type: 'image', src: '/images/Gallery/image_80.jpg' },
    { type: 'image', src: '/images/Gallery/image_81.jpg' },
    { type: 'image', src: '/images/Gallery/image_82.jpg' },
    { type: 'image', src: '/images/Gallery/image_83.jpg' },
    { type: 'image', src: '/images/Gallery/image_84.jpg' },
    { type: 'image', src: '/images/Gallery/image_85.jpg' },
    { type: 'image', src: '/images/Gallery/image_86.jpg' },
  ];

  selectedItem = signal<any>(null);

  openModal(item: any) { this.selectedItem.set(item); }
  closeModal() { this.selectedItem.set(null); }
}